# Generated by Django 4.2.3 on 2023-08-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcart',
            old_name='cart_ID',
            new_name='cartID',
        ),
    ]
