# Generated by Django 4.2.3 on 2023-08-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_cart_id_foodcart_cartid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcart',
            options={'verbose_name': 'FoodCart'},
        ),
    ]
