# Generated by Django 4.2.4 on 2023-09-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_verify_delete_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verify',
            old_name='user',
            new_name='username',
        ),
    ]
