# Generated by Django 4.2.4 on 2023-10-28 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime_of_payment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
