# Generated by Django 4.2.4 on 2023-10-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_order_datetime_of_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order'},
        ),
    ]
